name: flutter_app
description: "Fantasy Football App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # HTTP requests
  http: ^1.1.2

  # WebSocket / Real-time
  socket_io_client: ^2.0.3+1

  # Local storage
  shared_preferences: ^2.2.2

  # For JSON serialization
  json_annotation: ^4.8.1

  # Deep linking
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  # Optionally specify adaptive icon for Android
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"