default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store Connect"
  lane :build_and_upload do
    setup_ci if ENV['CI']
    
    # Create API key from environment variables
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"],
      is_key_content_base64: false,
      in_house: false
    )
    
    match(
      type: "appstore",
      readonly: false,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_BASIC_AUTHORIZATION"]),
      app_identifier: "com.jkap86.fantasyfootball",
      team_id: ENV["APPLE_TEAM_ID"],
      api_key: api_key
    )
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.jkap86.fantasyfootball" => "match AppStore com.jkap86.fantasyfootball"
        }
      }
    )
    
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
