default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store Connect"
  lane :build_and_upload do
    setup_ci if ENV['CI']
    
    match(
      type: "appstore",
      readonly: is_ci,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_BASIC_AUTHORIZATION"]),
      app_identifier: "com.jkap86.fantasyfootball",
      team_id: ENV["APPLE_TEAM_ID"]
    )
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.jkap86.fantasyfootball" => "match AppStore com.jkap86.fantasyfootball"
        }
      }
    )
    
    upload_to_testflight(
      api_key_path: "fastlane/api_key.json",
      skip_waiting_for_build_processing: true
    )
  end
end
